exclude: "^docs/|/migrations/|tests/data"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/emzeat/mz-lictools
    rev: v2.7.0
    hooks:
      - id: license-tools

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: uvx run ruff check
        language: system
        files: \.py$

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
