name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-blob: build_readme.py
      - name: Run cog
        env:
          ANDRLIK_TOKEN: ${{ secrets.ANDRLIK_TOKEN }}
        run: uvx --from cogapp cog -r README.md
      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push
